### ISSUE TITLE
[Feature Request] Auto-detect framework based on file type.

### ISSUE THREAD

**Issue by mikebronner** [alfredbirk/instant-docs#4]
Would be great if we could go directly to the relevant documentation for all languages where the documentation supports it. (we use the TALL stack)

**Comment by alfredbirk** [comment]
So if I understand correctly, you imagine a search where it will show results from multiple documentations at once? Like Laravel and Tailwind in the same search results for example?

**Comment by mikebronner** [comment]
@alfredbirk not quite, sorry for the confusion. I was thinking it might be helpful to preselect the framework based on the file type, but I guess that is not really possible with using multiple frameworks in the same file.
