### ISSUE TITLE
[Feature Request] Livewire Reference

### ISSUE THREAD

**Issue by mikebronner** [alfredbirk/instant-docs#6]
Would love to see livewire.laravel.com documentation references available.

**Comment by alfredbirk** [comment]
✅ I added alpine js docs

(unfortunately since https://livewire.laravel.com/ have blocked iframes, the docs can't be displayed directly inside vscode, so it will be opened in browser instead, but it's better than nothing)

**Comment by mikebronner** [comment]
Thank you! its excellent as a jumping pad to all reference documentation
